version: 0.0
os: windows
files:
  - source: .
    destination: c:\inetpub\wwwroot\eshop\
  - source: \Scripts\deletewebsite.ps1
    destination: c:\temp
  - source: \Scripts\installwebsite.ps1
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \Scripts\deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \Scripts\installwebsite.bat
      timeout: 180
